### ISSUE TITLE
 In the transition between 2 pages, the CSS file of the second page loads late causing a very bad effect.

### ISSUE THREAD

**Issue by AntonioMennuni** [swup/js-plugin#11]
I used swup to do a fade transition between 2 pages. I also used the 'SwupHeadPlugin' plugin to be able to provide both pages with a different css file. So far so good, but a bad effect happens in the transition. When the second page loads, you see the page without css for a short time and then load with CSS. I tried to use the puglin js-plugin, but didn't understand how to fix this problem. HELP !!
I leave you the entire code below as a pastebin link.

first page html file:
https://pastebin.com/Xrcf7EFC

first page css file:
https://pastebin.com/i7TFhVd2

second page html file:
https://pastebin.com/aRvGMBTW

second page css file:
https://pastebin.com/p9GS4DsD

**Comment by gmrchk** [comment]
Hey, this is just how it is with the head plugin. If you have separate styles for each page and no CSS file for general layout, the head plugin will end up replacing all CSS. In that process, there will be a moment when the browser has not styled at all. 

Either place all styles for all pages into one file loaded on all pages, or at least have a common layout styles file loaded on all pages.
