### ISSUE TITLE
[Bug]: Can't seem to install JS Plugin.

### ISSUE THREAD

**Issue by ryandc** [swup/js-plugin#34]
### What did you expect? 🧐

To run `npm install @swup/js-plugin` command found on the [doc page](https://swup.js.org/plugins/js-plugin/) and it install. 

### What actually happened? 😵‍💫

Error output and the plugin not installing.
Apologies if this is a simple issue of dependencies needing to be updated, I'm not familiar with contributions.

`npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated @babel/plugin-proposal-class-properties@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm ERR! code Z_DATA_ERROR
npm ERR! errno -3
npm ERR! zlib: incorrect data check`

### Swup and plugin versions 📝

- swup: 4.5.0
- Trying the latest 3.1.1

### URL to minimal reproduction 🔗

Locally currently

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Seems like `zlib` is having difficulty unpacking the downloaded file from npm, possibly from a corrupted file. Could this be a local network error? Just tried the install here and it seems to go through fine.

**Comment by ryandc** [comment]
Thanks for checking - I managed to install every other plugin I was getting set up with, but it's just this one that's proving problematic.

Saying that, it's obviously not an issue with the plugin so I'll close this.

**Comment by ryandc** [comment]
Feel free to delete the issue - It was down to a Node version requirement
