### ISSUE TITLE
[Bug]: Types for `from` and `to` are too restrictive

### ISSUE THREAD

**Issue by hirasso** [swup/js-plugin#36]
### What did you expect? 🧐

I'd expect `from` and `to` to accept any value compatible to [path-to-regexp](https://github.com/pillarjs/path-to-regexp):

- `string`
- `string[]`
- `RegExp`

### What actually happened? 😵‍💫

Only `string` is accepted, otherwise TypeScript complains

**Solution**

Use the type `Path` exported by `swup` for the types.

### Swup and plugin versions 📝

current versions

### URL to minimal reproduction 🔗

n/a

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Closing this as [we've been using](https://github.com/swup/js-plugin/blob/master/src/animations.ts#L12) the `Path` type exported by path-to-regexp for a while.
