### ISSUE TITLE
GSAP Timeline Example

### ISSUE THREAD

**Issue by bambootdj** [swup/js-plugin#5]
Hi there,

How Would a GSAP timeline be implemented?

I tried something like this but the timeline only played on the first transition.

```javascript
const transitions = [

	{
		from: '(.*)',
		to: '(.*)',
	  	out: (next) => {

			let tlPageTransitionOut = new TimelineMax({

				onComplete: next
			});
			tlPageTransitionOut
			.to(targetOne, 0.1, { /* Do Something */ }),
			tlPageTransitionOut.reverse();
			tlPageTransitionOut.play();
	  	},		  
	  	in: function(next) {

			let tlPageTransitionIn = new TimelineMax({

				onComplete: next
			});
			tlPageTransitionIn
			.to(targetOne, 0.1, { /* Do Something */ }),
			tlPageTransitionIn.reverse();
			tlPageTransitionIn.play();
			
	  	},
	}
];
```

Thanks for your patience! :)

**Comment by pixelmachine** [comment]
Next is a function so you should change lines `onComplete: next` to `onComplete: next()`.

**Comment by gmrchk** [comment]
Hey 👋

actually I don't think @pixelmachine is correct. Calling `next()` would trigger the next step right away. It seems like your timeline just doesn't finish in the `in` step. 

However, this is a question for GSAP guys, so I can't really help.

**Comment by pixelmachine** [comment]
> Calling next() would trigger the next step right away

No, that's wrong. The onComplete definition is a callback for when the GSAP timeline is complete. If you don't call `next()` at the end of the timeline then you will never trigger Swup's next steps. 

This is literally how my transitions look, except I'm using a different animation library.

**Comment by gmrchk** [comment]
Just remembered there is this thread https://github.com/swup/js-plugin/issues/2. Maybe a buggy version of gsap?
